substitutions:
  name: m5stack-atom-echo
  friendly_name: M5Stack Atom Echo

esphome:
  name: ${name}
  name_add_mac_suffix: true
  friendly_name: ${friendly_name}
  min_version: 2025.5.0

esp32:
  board: m5stack-atom
  cpu_frequency: 240MHz
  framework:
    type: esp-idf

logger:
api:

ota:
  - platform: esphome
    id: ota_esphome

wifi:
  ap:

captive_portal:

button:
  - platform: factory_reset
    id: factory_reset_btn
    name: Factory reset

i2s_audio:
  - id: i2s_audio_bus
    i2s_lrclk_pin: GPIO33
    i2s_bclk_pin: GPIO19

microphone:
  - platform: i2s_audio
    id: echo_microphone
    i2s_din_pin: GPIO23
    adc_type: external
    pdm: true
    sample_rate: 16000
    correct_dc_offset: true

speaker:
  - platform: i2s_audio
    id: echo_speaker
    i2s_dout_pin: GPIO22
    dac_type: external
    bits_per_sample: 16bit
    sample_rate: 16000
    channel: stereo  # The Echo has poor playback audio quality when using mono audio
    buffer_duration: 60ms

# Tracks active conversational session (internal). The UI switch below persists across boots.
# Also tracks TTS routing target
globals:
  - id: conversation_mode
    type: bool
    restore_value: no
    initial_value: 'false'
  - id: tts_target_media_player
    type: std::string
    restore_value: true
    initial_value: '""'

media_player:
  - platform: speaker
    name: None
    id: echo_media_player
    announcement_pipeline:
      speaker: echo_speaker
      format: WAV
    codec_support_enabled: false
    buffer_size: 6000
    volume_min: 0.4
    files:
      - id: timer_finished_wave_file
        file: https://github.com/esphome/wake-word-voice-assistants/raw/main/sounds/timer_finished.wav
    on_announcement:
      - if:
          condition:
            - microphone.is_capturing:
          then:
            - script.execute: stop_wake_word
      - light.turn_on:
          id: led
          blue: 100%
          red: 0%
          green: 0%
          brightness: 100%
          effect: none
    # Switch-aware idle behavior:
    on_idle:
      - if:
          condition:
            lambda: 'return id(conversation_mode);'
          then:
            # Conversational: immediately listen for follow-up (no wake word)
            - delay: 500ms
            - voice_assistant.start:
            - script.execute: conversation_timeout_timer
            - light.turn_on:
                id: led
                blue: 100%
                red: 0%
                green: 0%
                effect: "Slow Pulse"
          else:
            # Normal: restart wake word and restore LED
            - script.execute: start_wake_word
            - script.execute: reset_led

voice_assistant:
  id: va
  micro_wake_word:
  microphone:
    microphone: echo_microphone
    channels: 0
    gain_factor: 4
  media_player: echo_media_player
  noise_suppression_level: 2
  auto_gain: 31dBFS
  # Keep 5-minute context window in conversational mode; harmless when off
  conversation_timeout: 300s
  on_listening:
    - light.turn_on:
        id: led
        blue: 100%
        red: 0%
        green: 0%
        effect: "Slow Pulse"
  on_stt_vad_end:
    - light.turn_on:
        id: led
        blue: 100%
        red: 0%
        green: 0%
        effect: "Fast Pulse"
  on_tts_start:
    - light.turn_on:
        id: led
        blue: 100%
        red: 0%
        green: 0%
        brightness: 100%
        effect: none
  on_tts_end:
    - logger.log:
        format: "TTS Target Media Player value: %s"
        args: [id(tts_target_media_player).c_str()]
        level: DEBUG
    - if:
        condition:
          lambda: return !id(tts_target_media_player).empty();
        then:
          - logger.log:
              format: "Routing TTS to remote media player: %s"
              args: [id(tts_target_media_player).c_str()]
              level: DEBUG
          # Stop local playback
          - media_player.stop:
              id: echo_media_player
              announcement: true
          # Send to remote media player
          - homeassistant.service:
              service: media_player.play_media
              data:
                entity_id: !lambda return id(tts_target_media_player);
                media_content_id: !lambda return x;
                media_content_type: music
                announce: "true"
          - logger.log:
              format: "Sent TTS to remote media player"
              level: DEBUG

  # Enter conversational session when wake word hits, if switch is on
  on_wake_word_detected:
    - if:
        condition:
          switch.is_on: conversational
        then:
          - lambda: id(conversation_mode) = true;
          # Stop wake-word engine depending on location
          - if:
              condition:
                lambda: return id(wake_word_engine_location).state == "On device";
              then:
                - micro_wake_word.stop:
          - if:
              condition:
                lambda: return id(wake_word_engine_location).state == "In Home Assistant";
              then:
                - lambda: id(va).set_use_wake_word(false);
          - script.execute: conversation_timeout_timer
        else:
          - lambda: id(conversation_mode) = false;

  # Compatible with both modes; media_player.on_idle handles follow-ups or WW restart
  on_end:
    - wait_until:
        condition:
          - media_player.is_announcing:
        timeout: 0.5s

  on_error:
    - light.turn_on:
        id: led
        red: 100%
        green: 0%
        blue: 0%
        brightness: 100%
        effect: none
    - delay: 2s
    - lambda: id(conversation_mode) = false;
    - script.stop: conversation_timeout_timer
    - script.execute: reset_led

  on_client_connected:
    - delay: 2s
    - script.execute: start_wake_word

  on_client_disconnected:
    - script.execute: stop_wake_word
    - lambda: id(conversation_mode) = false;
    - script.stop: conversation_timeout_timer

  on_timer_finished:
    - script.execute: stop_wake_word
    - wait_until:
        not:
          microphone.is_capturing:
    - switch.turn_on: timer_ringing
    - light.turn_on:
        id: led
        red: 0%
        green: 100%
        blue: 0%
        brightness: 100%
        effect: "Fast Pulse"
    - wait_until:
        - switch.is_off: timer_ringing
    - light.turn_off: led
    - switch.turn_off: timer_ringing

binary_sensor:
  # Button:
  # short click - stop a timer; if no timer then restart wake word/VA as appropriate
  - platform: gpio
    pin:
      number: GPIO39
      inverted: true
    name: Button
    disabled_by_default: true
    entity_category: diagnostic
    id: echo_button
    on_multi_click:
      - timing:
          - ON for at least 50ms
          - OFF for at least 50ms
        then:
          - if:
              condition:
                switch.is_on: timer_ringing
              then:
                - switch.turn_off: timer_ringing
              else:
                - script.execute: start_wake_word
      - timing:
          - ON for at least 10s
        then:
          - button.press: factory_reset_btn

light:
  - platform: esp32_rmt_led_strip
    id: led
    name: None
    disabled_by_default: true
    entity_category: config
    pin: GPIO27
    default_transition_length: 0s
    chipset: SK6812
    num_leds: 1
    rgb_order: grb
    effects:
      - pulse:
          name: "Slow Pulse"
          transition_length: 250ms
          update_interval: 250ms
          min_brightness: 50%
          max_brightness: 100%
      - pulse:
          name: "Fast Pulse"
          transition_length: 100ms
          update_interval: 100ms
          min_brightness: 50%
          max_brightness: 100%

script:
  # Sliding window timeout that ends conversational session (stable & simple)
  - id: conversation_timeout_timer
    mode: restart
    then:
      - delay: 15s
      - logger.log: "Conversation timeout - returning to wake word mode"
      - lambda: id(conversation_mode) = false;
      - voice_assistant.stop:
      # Restart wake-word engine based on engine location
      - if:
          condition:
            lambda: return id(wake_word_engine_location).state == "On device";
          then:
            - delay: 100ms
            - lambda: id(va).set_use_wake_word(false);
            - micro_wake_word.start:
      - if:
          condition:
            lambda: return id(wake_word_engine_location).state == "In Home Assistant";
          then:
            - delay: 100ms
            - lambda: id(va).set_use_wake_word(true);
            - voice_assistant.start_continuous:
      - script.execute: reset_led

  - id: reset_led
    then:
      - if:
          condition:
            - lambda: return id(wake_word_engine_location).state == "On device";
            - switch.is_on: use_listen_light
          then:
            - light.turn_on:
                id: led
                red: 100%
                green: 89%
                blue: 71%
                brightness: 60%
                effect: none
          else:
            - if:
                condition:
                  - lambda: return id(wake_word_engine_location).state != "On device";
                  - switch.is_on: use_listen_light
                then:
                  - light.turn_on:
                      id: led
                      red: 0%
                      green: 100%
                      blue: 100%
                      brightness: 60%
                      effect: none
                else:
                  - light.turn_off: led

  - id: start_wake_word
    then:
      - if:
          condition:
            and:
              - not:
                  - voice_assistant.is_running:
              - lambda: return id(wake_word_engine_location).state == "On device";
          then:
            - lambda: id(va).set_use_wake_word(false);
            - micro_wake_word.start:
      - if:
          condition:
            and:
              - not:
                  - voice_assistant.is_running:
              - lambda: return id(wake_word_engine_location).state == "In Home Assistant";
          then:
            - lambda: id(va).set_use_wake_word(true);
            - voice_assistant.start_continuous:

  - id: stop_wake_word
    then:
      - if:
          condition:
            lambda: return id(wake_word_engine_location).state == "In Home Assistant";
          then:
            - lambda: id(va).set_use_wake_word(false);
            - voice_assistant.stop:
      - if:
          condition:
            lambda: return id(wake_word_engine_location).state == "On device";
          then:
            - micro_wake_word.stop:

switch:
  # Your new mode toggle (persists across boots; stable & easy)
  - platform: template
    name: Conversational
    id: conversational
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF  # restores last state; defaults OFF if unknown
    entity_category: config
    on_turn_on:
      - lambda: id(conversation_mode) = true;
    on_turn_off:
      - lambda: id(conversation_mode) = false;

  - platform: template
    name: Use listen light
    id: use_listen_light
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    entity_category: config
    on_turn_on:
      - script.execute: reset_led
    on_turn_off:
      - script.execute: reset_led

  - platform: template
    id: timer_ringing
    optimistic: true
    restore_mode: ALWAYS_OFF
    on_turn_off:
      # Turn off repeat and inter-repeat delay
      - lambda: |-
              id(echo_media_player)
                ->make_call()
                .set_command(media_player::MediaPlayerCommand::MEDIA_PLAYER_COMMAND_REPEAT_OFF)
                .set_announcement(true)
                .perform();
              id(echo_media_player)->set_playlist_delay_ms(speaker::AudioPipelineType::ANNOUNCEMENT, 0);
      - media_player.stop:
          announcement: true
    on_turn_on:
      # Repeat alarm with 1000 ms gap
      - lambda: |-
            id(echo_media_player)
              ->make_call()
              .set_command(media_player::MediaPlayerCommand::MEDIA_PLAYER_COMMAND_REPEAT_ONE)
              .set_announcement(true)
              .perform();
            id(echo_media_player)->set_playlist_delay_ms(speaker::AudioPipelineType::ANNOUNCEMENT, 1000);
      - media_player.speaker.play_on_device_media_file:
          media_file: timer_finished_wave_file
          announcement: true
      - delay: 15min
      - switch.turn_off: timer_ringing

text:
  - platform: template
    name: "TTS target media player"
    id: tts_target_media_player_text
    internal: false
    optimistic: true
    min_length: 0
    max_length: 100
    mode: text
    entity_category: config
    restore_value: true
    initial_value: ""
    on_value:
      then:
        - lambda: |-
            id(tts_target_media_player) = x;
        - logger.log:
            format: "TTS target media player set to: %s"
            args: [ x.c_str() ]
            level: DEBUG

select:
  - platform: template
    entity_category: config
    name: Wake word engine location
    id: wake_word_engine_location
    optimistic: true
    restore_value: true
    options:
      - In Home Assistant
      - On device
    initial_option: On device
    on_value:
      - if:
          condition:
            lambda: return x == "In Home Assistant";
          then:
            - micro_wake_word.stop:
            - delay: 500ms
            - lambda: id(va).set_use_wake_word(true);
            - voice_assistant.start_continuous:
      - if:
          condition:
            lambda: return x == "On device";
          then:
            - lambda: id(va).set_use_wake_word(false);
            - voice_assistant.stop:
            - delay: 500ms
            - micro_wake_word.start:

micro_wake_word:
  on_wake_word_detected:
    - voice_assistant.start:
        wake_word: !lambda return wake_word;
  vad:
  models:
    - model: okay_nabu
    - model: hey_mycroft
    - model: hey_jarvis
